 2024-11-24 21:56:13,118 - INFO - Initialized Tests class. Object ID: 0
2024-11-24 21:56:13,118 - INFO - Data passed  ID: 0
2024-11-24 21:56:13,118 - INFO - Labels and k passed all checks. ID: 0
2024-11-24 21:56:14,930 - WARNING - Mismatch in center lengths.
2024-11-24 21:56:14,930 - DEBUG - Mean absolute error: 2.606685
2024-11-24 21:56:14,930 - DEBUG -  conditons result: 2.6066849816849813 < 0.5 and True and 0.3333333333333333>=1
2024-11-24 21:56:15,796 - WARNING - Mismatch in center lengths.
2024-11-24 21:56:15,796 - DEBUG - Mean absolute error: 1.152717
2024-11-24 21:56:15,796 - DEBUG -  conditons result: 1.1527167277167272 < 0.5 and True and 0.3333333333333333>=1
2024-11-24 21:56:15,796 - DEBUG - Groups differ: [11, 0] != [19, 16]
2024-11-24 21:56:16,285 - WARNING - Mismatch in center lengths.
2024-11-24 21:56:16,285 - DEBUG - Mean absolute error: 0.527778
2024-11-24 21:56:16,285 - DEBUG -  conditons result: 0.5277777777777777 < 0.5 and True and 0.6666666666666666>=1
2024-11-24 21:56:16,285 - DEBUG - Groups differ: [28, 14] != [27, 18]
2024-11-24 21:56:16,827 - WARNING - Mismatch in center lengths.
2024-11-24 21:56:16,827 - DEBUG - Mean absolute error: 0.000000
2024-11-24 21:56:16,827 - DEBUG -  conditons result: 0.0 < 0.5 and True and 1.3333333333333333>=1
2024-11-24 21:56:16,827 - DEBUG - Groups are stable.
2024-11-24 21:56:17,295 - INFO - Initialized Tests class. Object ID: 0
2024-11-24 21:56:17,296 - INFO - Test instance 0 created successfully.
2024-11-24 21:56:17,296 - INFO - Initialized Tests class. Object ID: 1
2024-11-24 21:56:17,296 - INFO - Test instance 1 created successfully.
2024-11-24 21:56:17,296 - INFO - Initialized Tests class. Object ID: 2
2024-11-24 21:56:17,296 - INFO - Test instance 2 created successfully.
2024-11-24 21:56:17,296 - INFO - Initialized Tests class. Object ID: 3
2024-11-24 21:56:17,296 - INFO - Test instance 3 created successfully.
2024-11-24 21:56:17,296 - INFO - Initialized Tests class. Object ID: 4
2024-11-24 21:56:17,296 - INFO - Test instance 4 created successfully.
2024-11-24 21:56:17,296 - INFO - Initialized Tests class. Object ID: 5
2024-11-24 21:56:17,296 - INFO - Test instance 5 created successfully.
2024-11-24 21:56:17,296 - INFO - Data passed  ID: 0
2024-11-24 21:56:17,296 - INFO - Test instance 0 passed data_errors.
2024-11-24 21:56:17,296 - ERROR - Element type is not a list: <class 'tuple'>  ID: 1
2024-11-24 21:56:17,296 - ERROR - Exception in data_errors.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 42, in data_errors
    raise TestKmeans_data(
Tests_Kmeans.TestKmeans_data: [93mObject type error  with: [91mObject type supposed to be a list, not <class 'tuple'> , 
 at index : 2
2024-11-24 21:56:17,297 - ERROR - Test instance 1 failed data_errors: [93mObject type error  with: [91mObject type supposed to be a list, not <class 'tuple'> , 
 at index : 2
2024-11-24 21:56:17,297 - ERROR - Inconsistent data lengths: 4 != 5  ID: 2
2024-11-24 21:56:17,297 - ERROR - Exception in data_errors.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 50, in data_errors
    raise TestKmeans_data(
Tests_Kmeans.TestKmeans_data: [93mDifferent length  with: [91mObjects with 4 != 5 , 
 at index : 1 and 0
2024-11-24 21:56:17,297 - ERROR - Test instance 2 failed data_errors: [93mDifferent length  with: [91mObjects with 4 != 5 , 
 at index : 1 and 0
2024-11-24 21:56:17,297 - ERROR - Invalid element types in data: ['2', 3, 4, 5]   ID: 3
2024-11-24 21:56:17,297 - ERROR - Exception in data_errors.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 58, in data_errors
    raise TestKmeans_data(
Tests_Kmeans.TestKmeans_data: [93mWrong type  with: [91mError occurred for: ['2', 3, 4, 5], all numbers must be int or float , 
 at index : 1
2024-11-24 21:56:17,297 - ERROR - Test instance 3 failed data_errors: [93mWrong type  with: [91mError occurred for: ['2', 3, 4, 5], all numbers must be int or float , 
 at index : 1
2024-11-24 21:56:17,297 - ERROR - Invalid element types in data: ['2', 3, 4, 5]   ID: 4
2024-11-24 21:56:17,297 - ERROR - Exception in data_errors.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 58, in data_errors
    raise TestKmeans_data(
Tests_Kmeans.TestKmeans_data: [93mWrong type  with: [91mError occurred for: ['2', 3, 4, 5], all numbers must be int or float , 
 at index : 1
2024-11-24 21:56:17,298 - ERROR - Test instance 4 failed data_errors: [93mWrong type  with: [91mError occurred for: ['2', 3, 4, 5], all numbers must be int or float , 
 at index : 1
2024-11-24 21:56:17,298 - INFO - Data passed  ID: 5
2024-11-24 21:56:17,298 - INFO - Test instance 5 passed data_errors.
2024-11-24 21:56:17,298 - ERROR - k is larger  or equal to number of labels and less than data: k=3, labels=26 data=3   ID: 0
2024-11-24 21:56:17,298 - ERROR - Exception in labels_K_errors for Object ID: 0.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 99, in labels_K_errors
    raise TestKmeans_area(
Tests_Kmeans.TestKmeans_area: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,298 - ERROR - Test instance 0 failed labels_K_errors: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,298 - ERROR - k is larger  or equal to number of labels and less than data: k=3, labels=26 data=3   ID: 1
2024-11-24 21:56:17,298 - ERROR - Exception in labels_K_errors for Object ID: 1.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 99, in labels_K_errors
    raise TestKmeans_area(
Tests_Kmeans.TestKmeans_area: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,299 - ERROR - Test instance 1 failed labels_K_errors: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,299 - ERROR - k is larger  or equal to number of labels and less than data: k=3, labels=26 data=4   ID: 2
2024-11-24 21:56:17,299 - ERROR - Exception in labels_K_errors for Object ID: 2.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 99, in labels_K_errors
    raise TestKmeans_area(
Tests_Kmeans.TestKmeans_area: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,299 - ERROR - Test instance 2 failed labels_K_errors: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,299 - ERROR - k is larger  or equal to number of labels and less than data: k=3, labels=26 data=4   ID: 3
2024-11-24 21:56:17,299 - ERROR - Exception in labels_K_errors for Object ID: 3.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 99, in labels_K_errors
    raise TestKmeans_area(
Tests_Kmeans.TestKmeans_area: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,299 - ERROR - Test instance 3 failed labels_K_errors: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,299 - ERROR - k is larger  or equal to number of labels and less than data: k=3, labels=26 data=4   ID: 4
2024-11-24 21:56:17,299 - ERROR - Exception in labels_K_errors for Object ID: 4.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 99, in labels_K_errors
    raise TestKmeans_area(
Tests_Kmeans.TestKmeans_area: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,299 - ERROR - Test instance 4 failed labels_K_errors: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,299 - ERROR - k is larger  or equal to number of labels and less than data: k=3, labels=26 data=5   ID: 5
2024-11-24 21:56:17,299 - ERROR - Exception in labels_K_errors for Object ID: 5.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 99, in labels_K_errors
    raise TestKmeans_area(
Tests_Kmeans.TestKmeans_area: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,299 - ERROR - Test instance 5 failed labels_K_errors: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,299 - WARNING - Centers have inconsistent lengths.
2024-11-24 21:56:17,299 - INFO - Continuation condition centers test 0: False
2024-11-24 21:56:17,299 - WARNING - Mismatch in center lengths.
2024-11-24 21:56:17,299 - WARNING - Previous and current centers have different lengths.
2024-11-24 21:56:17,299 - INFO - Continuation condition centers test 1: False
2024-11-24 21:56:17,299 - WARNING - Mismatch in center lengths.
2024-11-24 21:56:17,299 - DEBUG - Mean absolute error: 2.000000
2024-11-24 21:56:17,299 - DEBUG -  conditons result: 2.0 < 0.5 and True and 0.6666666666666666>=1
2024-11-24 21:56:17,299 - INFO - Continuation condition centers test 2: False
2024-11-24 21:56:17,299 - WARNING - Mismatch in center lengths.
2024-11-24 21:56:17,299 - DEBUG - Mean absolute error: 2.666667
2024-11-24 21:56:17,299 - DEBUG -  conditons result: 2.6666666666666665 < 0.5 and True and 0.3333333333333333>=1
2024-11-24 21:56:17,299 - INFO - Continuation condition centers test 3: False
2024-11-24 21:56:17,302 - ERROR - Error in continuation condition groups test 0: 'int' object is not iterable
2024-11-24 21:56:17,302 - DEBUG - Groups differ: 2 != 3
2024-11-24 21:56:17,302 - INFO - Continuation condition groups test 1: False
2024-11-24 21:56:17,302 - INFO - Initialized Tests class. Object ID: 0
2024-11-24 21:56:17,302 - INFO - Test instance 0 created successfully.
2024-11-24 21:56:17,302 - INFO - Initialized Tests class. Object ID: 1
2024-11-24 21:56:17,302 - INFO - Test instance 1 created successfully.
2024-11-24 21:56:17,302 - INFO - Initialized Tests class. Object ID: 2
2024-11-24 21:56:17,302 - INFO - Test instance 2 created successfully.
2024-11-24 21:56:17,302 - INFO - Initialized Tests class. Object ID: 3
2024-11-24 21:56:17,302 - INFO - Test instance 3 created successfully.
2024-11-24 21:56:17,302 - INFO - Initialized Tests class. Object ID: 4
2024-11-24 21:56:17,302 - INFO - Test instance 4 created successfully.
2024-11-24 21:56:17,302 - INFO - Initialized Tests class. Object ID: 5
2024-11-24 21:56:17,302 - INFO - Test instance 5 created successfully.
2024-11-24 21:56:17,302 - INFO - Data passed  ID: 0
2024-11-24 21:56:17,302 - INFO - Test instance 0 passed data_errors.
2024-11-24 21:56:17,302 - ERROR - Element type is not a list: <class 'tuple'>  ID: 1
2024-11-24 21:56:17,302 - ERROR - Exception in data_errors.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 42, in data_errors
    raise TestKmeans_data(
Tests_Kmeans.TestKmeans_data: [93mObject type error  with: [91mObject type supposed to be a list, not <class 'tuple'> , 
 at index : 2
2024-11-24 21:56:17,303 - ERROR - Test instance 1 failed data_errors: [93mObject type error  with: [91mObject type supposed to be a list, not <class 'tuple'> , 
 at index : 2
2024-11-24 21:56:17,303 - ERROR - Inconsistent data lengths: 4 != 5  ID: 2
2024-11-24 21:56:17,303 - ERROR - Exception in data_errors.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 50, in data_errors
    raise TestKmeans_data(
Tests_Kmeans.TestKmeans_data: [93mDifferent length  with: [91mObjects with 4 != 5 , 
 at index : 1 and 0
2024-11-24 21:56:17,303 - ERROR - Test instance 2 failed data_errors: [93mDifferent length  with: [91mObjects with 4 != 5 , 
 at index : 1 and 0
2024-11-24 21:56:17,303 - ERROR - Invalid element types in data: ['2', 3, 4, 5]   ID: 3
2024-11-24 21:56:17,303 - ERROR - Exception in data_errors.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 58, in data_errors
    raise TestKmeans_data(
Tests_Kmeans.TestKmeans_data: [93mWrong type  with: [91mError occurred for: ['2', 3, 4, 5], all numbers must be int or float , 
 at index : 1
2024-11-24 21:56:17,303 - ERROR - Test instance 3 failed data_errors: [93mWrong type  with: [91mError occurred for: ['2', 3, 4, 5], all numbers must be int or float , 
 at index : 1
2024-11-24 21:56:17,303 - ERROR - Invalid element types in data: ['2', 3, 4, 5]   ID: 4
2024-11-24 21:56:17,303 - ERROR - Exception in data_errors.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 58, in data_errors
    raise TestKmeans_data(
Tests_Kmeans.TestKmeans_data: [93mWrong type  with: [91mError occurred for: ['2', 3, 4, 5], all numbers must be int or float , 
 at index : 1
2024-11-24 21:56:17,303 - ERROR - Test instance 4 failed data_errors: [93mWrong type  with: [91mError occurred for: ['2', 3, 4, 5], all numbers must be int or float , 
 at index : 1
2024-11-24 21:56:17,303 - INFO - Data passed  ID: 5
2024-11-24 21:56:17,303 - INFO - Test instance 5 passed data_errors.
2024-11-24 21:56:17,303 - ERROR - k is larger  or equal to number of labels and less than data: k=3, labels=26 data=3   ID: 0
2024-11-24 21:56:17,303 - ERROR - Exception in labels_K_errors for Object ID: 0.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 99, in labels_K_errors
    raise TestKmeans_area(
Tests_Kmeans.TestKmeans_area: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,303 - ERROR - Test instance 0 failed labels_K_errors: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,304 - ERROR - k is larger  or equal to number of labels and less than data: k=3, labels=26 data=3   ID: 1
2024-11-24 21:56:17,304 - ERROR - Exception in labels_K_errors for Object ID: 1.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 99, in labels_K_errors
    raise TestKmeans_area(
Tests_Kmeans.TestKmeans_area: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,304 - ERROR - Test instance 1 failed labels_K_errors: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,304 - ERROR - k is larger  or equal to number of labels and less than data: k=3, labels=26 data=4   ID: 2
2024-11-24 21:56:17,304 - ERROR - Exception in labels_K_errors for Object ID: 2.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 99, in labels_K_errors
    raise TestKmeans_area(
Tests_Kmeans.TestKmeans_area: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,304 - ERROR - Test instance 2 failed labels_K_errors: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,304 - ERROR - k is larger  or equal to number of labels and less than data: k=3, labels=26 data=4   ID: 3
2024-11-24 21:56:17,304 - ERROR - Exception in labels_K_errors for Object ID: 3.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 99, in labels_K_errors
    raise TestKmeans_area(
Tests_Kmeans.TestKmeans_area: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,304 - ERROR - Test instance 3 failed labels_K_errors: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,304 - ERROR - k is larger  or equal to number of labels and less than data: k=3, labels=26 data=4   ID: 4
2024-11-24 21:56:17,304 - ERROR - Exception in labels_K_errors for Object ID: 4.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 99, in labels_K_errors
    raise TestKmeans_area(
Tests_Kmeans.TestKmeans_area: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,304 - ERROR - Test instance 4 failed labels_K_errors: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,304 - ERROR - k is larger  or equal to number of labels and less than data: k=3, labels=26 data=5   ID: 5
2024-11-24 21:56:17,304 - ERROR - Exception in labels_K_errors for Object ID: 5.
Traceback (most recent call last):
  File "C:\Program Files\Pulpit\Projekt_Python\K_means\Tests_Kmeans.py", line 99, in labels_K_errors
    raise TestKmeans_area(
Tests_Kmeans.TestKmeans_area: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,305 - ERROR - Test instance 5 failed labels_K_errors: [93mk count of clusters must be less than or equal to the labels you provide  at: 3,26 in data
2024-11-24 21:56:17,305 - WARNING - Centers have inconsistent lengths.
2024-11-24 21:56:17,305 - INFO - Continuation condition centers test 0: False
2024-11-24 21:56:17,305 - WARNING - Mismatch in center lengths.
2024-11-24 21:56:17,305 - WARNING - Previous and current centers have different lengths.
2024-11-24 21:56:17,305 - INFO - Continuation condition centers test 1: False
2024-11-24 21:56:17,305 - WARNING - Mismatch in center lengths.
2024-11-24 21:56:17,305 - DEBUG - Mean absolute error: 2.000000
2024-11-24 21:56:17,305 - DEBUG -  conditons result: 2.0 < 0.5 and True and 0.6666666666666666>=1
2024-11-24 21:56:17,305 - INFO - Continuation condition centers test 2: False
2024-11-24 21:56:17,305 - WARNING - Mismatch in center lengths.
2024-11-24 21:56:17,305 - DEBUG - Mean absolute error: 2.666667
2024-11-24 21:56:17,305 - DEBUG -  conditons result: 2.6666666666666665 < 0.5 and True and 0.3333333333333333>=1
2024-11-24 21:56:17,305 - INFO - Continuation condition centers test 3: False
2024-11-24 21:56:17,305 - ERROR - Error in continuation condition groups test 0: 'int' object is not iterable
2024-11-24 21:56:17,305 - DEBUG - Groups differ: 2 != 3
2024-11-24 21:56:17,306 - INFO - Continuation condition groups test 1: False
